# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 05:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20190606_0513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='authors',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='mod_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_comments',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='n_pingbacks',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
    ]
