# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-06-06 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20190606_0554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='blog',
        ),
        migrations.AddField(
            model_name='entry',
            name='blog',
            field=models.ManyToManyField(to='webapp.Blog'),
        ),
    ]
